  factorio:
   build: .
   container_name: factorio
   restart: always
   ports: 
     - '8080:80'
     - '444:443'
     - '34197:34197/udp'
   volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./saves:/opt/factorio/saves
    - ./mods:/opt/factorio/mods
    - ./config:/opt/factorio/config
    - ./security:/security
